apps/resources/urls.py
from django.urls import path
from . import views

app_name = "resources"
urlpatterns = [
    path("", views.home_page, name="home-page"),
    path("resource/<int:id>", views.resource_detail, name="resource-detail"),
    path("resource/post/", views.post_resource, name="post-resource"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.resources.urls", namespace="resources")),
    path("users/", include("apps.user.urls")),
]

templates/resources/home.html
{% extends 'base.html' %}
<!-- in case you are using static -->
{% load static %}
<!-- override title -->
{% block title %}{{ block.super }} - Home{% endblock title %}
<!-- override main content -->
{% block content %}
<h1 class="head">Welcome to ResourceShare</h1>

<p>{{res_cnt}} resources and counting!</p>

<h2>All Users</h2>
<p>{{user_cnt}} Users and counting!</p>
<h2>All Categories</h2>
<ol>
  {% for cat_cnt in cnt_per_cat %}
  <li>{{cat_cnt.cat_id__cat}}: {{cat_cnt.cnt}}</li>
  {% endfor %}
</ol>
{% endblock content %}

templates/resources/post.html
{% extends 'base.html' %} {% load static %}
<!---->
{% block title %}{{ block.super }} - Post {% endblock title %}
<!---->
{% block stylesheet %}
<!---->
{{ block.super}}
<!---->
<link rel="stylesheet" type="text/css" href="{% static "css/form.css" %}" />
<!---->
{% endblock stylesheet %}
<!---->
{% block content%}
<h1 class="head">Share your resource</h1>
<div class="post-form">
  <form method="post" action="{% url 'resources:post-resource' %}">
    {% csrf_token %}
    <div class="form-element">
      <label for="title_input">Title</label>
      <input
        id="title_input"
        type="text"
        name="title_input"
        value=""
        placeholder="Enter title"
      />
    </div>
    <div class="form-element">
      <label for="link_input">Link</label>
      <input
        id="link_input"
        type="url"
        name="link_input"
        value=""
        placeholder="Enter URL"
      />
    </div>
    <div class="form-element">
      <label for="description_textarea">Description</label><br />
      <textarea
        id="description_textarea"
        type="textarea"
        name="description_textarea"
        value=""
        placeholder="Enter Description"
      ></textarea>
      <hr />
      <div class="form-category">
        <h3>Category</h3>
        <div>
          <input id="cat_pl_radio" type="radio" value="pl" />
          <label for="cat_pl_radio">Programming Language</label>
        </div>
        <div>
          <input id="cat_db_radio" type="radio" value="db" />
          <label for="cat_pl_radio">Databases</label>
        </div>
      </div>
      <div class="form-tags">
        <h3 class="head">Tags</h3>
        <div class="tag-pl">
          <div>
            <input
              id="tag_python_input"
              name="tag_python_input"
              type="checkbox"
            />
            <label for="tag_python_input">Python</label>
          </div>
          <div>
            <input
              id="tag_django_input"
              name="tag_django_input"
              type="checkbox"
            />
            <label for="tag_django_input">Django</label>
          </div>
          <div>
            <input id="tag_sql_input" name="tag_sql_input" type="checkbox" />
            <label for="tag_sql_input">SQL</label>
          </div>
          <div>
            <input
              id="tag_postgresql_input"
              name="tag_postgresql_input"
              type="checkbox"
            />
            <label for="tag_postgresql_input">Python</label>
          </div>
        </div>
        <div class="tag-level">
          <div>
            <input
              id="tag_beginner_input"
              name="tag_beginner_input"
              type="checkbox"
            />
            <label for="tag_beginner_input">Beginner</label>
          </div>
          <div>
            <input
              id="tag_mid_level_input"
              name="tag_mid_level_input"
              type="checkbox"
            />
            <label for="tag_mid_level_input">Mid-level</label>
          </div>
          <div>
            <input
              id="tag_advanced_input"
              name="tag_advanced_input"
              type="checkbox"
            />
            <label for="tag_advanced_input">SQL</label>
          </div>
        </div>
        <div class="tag-cost">
          <div>
            <input id="tag_cost_input" name="tag_cost_input" type="checkbox" />
            <label for="tag_cost_input">Cost</label>
          </div>
          <div>
            <input id="tag_free_input" name="tag_free_input" type="checkbox" />
            <label for="tag_free_input">Free</label>
          </div>
        </div>
      </div>
    </div>
    <input type="submit" value="Submit" />
  </form>
</div>
{% endblock content %} {% comment %}
<select id="tags_select" name="tags" multiple>
  <optgroup label="programming-language">
    <option value="python">Python</option>
    <option value="django">Django</option>
    <option value="sql">SQL</option>
    <option value="postgresql">PostgreSQL</option>
  </optgroup>
  <optgroup label="level">
    <option value="beginner">Beginner</option>
    <option value="mid-level">Mid-level</option>
    <option value="advanced">Advanced</option>
  </optgroup>
  <optgroup label="cost">
    <option value="free">Free</option>
    <option value="paid">Paid</option>
  </optgroup>
</select>
{% endcomment %}

templates/resources/posts.html
{% extends 'base.html' %} {% load static %}
<!---->
{% block title %}{{ block.super }} - Post {% endblock title %}
<!---->
{% block stylesheet %}
<!---->
{{ block.super}}
<!---->
<link rel="stylesheet" type="text/css" href="{% static "css/form.css" %}" />
<!---->
{% endblock stylesheet %}
<!---->
{% block content%}
<h1 class="head">Share your resource</h1>
<div class="post-form">
  <form method="post" action="{% url 'resources:post-resource' %}">
    {% csrf_token %} {{ form }} {# {{ form.as_p }} #}
    <input type="submit" value="Submit" />
  </form>
</div>
{% endblock content %}

templates/resources/resource_detail.html
{% load custom_filter %}
<!DOCTYPE html>
<html>
  <body>
    <h1>{{res.title}}</h1>
    <p><b>User</b>: {{res.user_id.username.capitalize}}</p>
    <p><b>Link</b>: {{res.link}}</p>
    <p><b>Description</b>: {{res.description}}</p>
    <p><b>Category</b>: {{res.cat_id.cat}}</p>
    <p><b>Tags</b>: {{res.get_all_tags|dash_separator}}</p>
    <p><b>Tags</b>: {{res.get_all_tags|separator:" "}}</p>
  </body>
</html>