apps/resources/urls.py
from django.urls import path
from . import views

app_name = "resources"
urlpatterns = [
    path("", views.home_page, name="home-page"),
    path("resource/<int:id>", views.resource_detail, name="resource-detail"),
    path("resource/post/", views.post_resource, name="post-resource"),
]

apps/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("list/", views.list_users, name="list-users"),
    path("login/", views.login_view, name="login-view"),
    path("profile/", views.profile, name="profile"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.resources.urls", namespace="resources")),
    path("users/", include("apps.user.urls")),
]

apps/user/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    title = models.CharField(max_length=100, null=True, help_text="Your profession")
    bio = models.TextField(default="")

apps/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from .models import User


# Create your views here.
def list_users(request):
    users = User.objects.all()

    context = {"users": users}
    return render(request, "user/list_users.html", context)


def list_users_old(request):
    users = User.objects.all()
    user_cnt = users.count()

    context = {"users": users, "user_cnt": user_cnt}
    return render(request, "user/list_users.html", context)


def login_view(request):
    # unbound state
    error_message = None
    form = AuthenticationForm()

    if request.method == "POST":
        # bound state
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")

            # Authenticate the user.

            user = authenticate(
                username=username,
                password=password,
            )
            if user is not None:
                # retain user's id in the session
                login(request, user)
                # we shall create the profile url/view and template
                return redirect("profile")

        else:
            error_message = "Sorry, something went wrong. Try again"

    context = {"form": form, "error_message": error_message}

    return render(request, "user/login.html", context)


@login_required
def profile(request):
    context = {"user": request.user}
    return render(request, "user/profile.html", context)

templates/user/list_users.html
<!DOCTYPE html>

<html>
  <body>
    <div>
      {% comment %}
      <span>We are proud of our {{ users|length }} users</span>
      {% endcomment %}
      <span>We are proud of our {{ users|length }} users</span>

      <ul>
        {% for user in users %}
        <li>{{ user.username }}</li>
        {% endfor %}
      </ul>
    </div>
  </body>
</html>

templates/user/login.html
{% extends 'base.html' %} {% load static %}
<!---->
{% block title %}{{ block.super }} - Login {% endblock title %}
<!---->
{% block stylesheet %}
<!---->
{{ block.super}}
<!---->
<link rel="stylesheet" type="text/css" href="{% static "css/form.css" %}" />
<!---->
{% endblock stylesheet %}
<!---->
{% block content%}
<h1 class="head">Log In</h1>
<div class="post-form">
  <form method="post">
    {% csrf_token %} {{ form }} {# {{ form.as_p }} #}
    <input type="submit" value="Submit" />
  </form>
</div>
{% endblock content %}

templates/user/profile.html
{% extends 'base.html' %}
<!-- in case you are using static -->
{% load static %}
<!-- override title -->
{% block title %}{{ block.super }} - Profile{% endblock title %}
<!-- override main content -->
{% block content %}
<h1 class="head">Welcome to {{ request.user.username }}</h1>

<div class="viewed-resources">
  <h3>Viewed Resources</h3>

  {% for resource_id, resource_title in request.session.viewed_resources %}
  <a href={% url 'resources:resource-detail' id=resource_id %}>{{resource_title}}</a>
  <br />

   {% empty %}
      <p>No recently viewed resources</p>
  
  {% endfor %}
</div>
{% endblock content %}